scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']      
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:3000']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
